//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreatLakesAlliance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetEventData
    {
        public string eventId { get; set; }
        public string eventName { get; set; }
        public Nullable<System.DateTime> eventStartDateTime { get; set; }
        public Nullable<System.DateTime> eventEndDateTime { get; set; }
        public Nullable<int> volunteersNeeded { get; set; }
        public string location { get; set; }
    }
}
